---
# tasks file for ansible-user
- name: Add ansible user without password
  user:
    name: ansible
    create_home: yes
    shell: /bin/bash
    password: "*"
    state: present
- name: Grant sudo privileges to the user
  lineinfile:
   dest: /etc/sudoers
   line: "ansible ALL=(ALL:ALL) NOPASSWD: ALL"
   state: present
   validate: visudo -cf %s
- name: Add SSH public key to user's authorized_keys
  authorized_key:
    user: ansible
    state: present
    key: "{{ ssh_public_key }}"