---
- hosts: 127.0.0.1
  become: true
  vars_files:
    - vars.yml
  tasks:
    - name: Install a opensearch.deb package 
      apt:
       deb: "https://artifacts.opensearch.org/releases/bundle/opensearch/{{openSearch_version}}/opensearch-{{openSearch_version}}-linux-x64.deb"
      notify: enable and start opensearch
    - name: enable and start opensearch
      service:
        name: opensearch
        state: restarted
        enabled: true
    - name: if you see this you have installed opensearch
      shell: curl -X GET https://localhost:9200 -u 'admin:admin' --insecure
      register: ps
    #- debug: var=ps.stdout_lines
     # Print the shell task's stdout.
   # - debug: msg={{ ps.stdout }}

    # Print all contents of the shell task's output.
    - debug: var=ps
        
        

      
  #https://artifacts.opensearch.org/releases/bundle/opensearch/2.9.0/opensearch-2.9.0-linux-x64.tar.gz
